version: 2.1

workflows:
  version: 2
  validate:
    jobs:
      - test

jobs:
  test:
    machine: true
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run setup
      - run: npm test
